# This is the basic workflow to show thw manual trigger
name: Manual-Actions-Workflow

on:
  workflow_dispatch:
    inputs:
      loglevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Say Something
      run: echo "Hi, I have been manually triggered!"
    
    - run: |
        echo "Log level: ${{ github.event.inputs.loglevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"
    
