# This is the basic workflow to show thw manual trigger
name: Manual-Actions-Workflow

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Say Something
      run: echo "Hi, I have been manually triggered!"
